### ISSUE TITLE
Договорная цена

### ISSUE THREAD

**Issue by ingumsky** [vne/rex-format#6]
Мне кажется, имеет смысл договорную цену указывать явно, например, с помощью атрибута **negotiable** для тега **price** (*boolean*, по умолчанию *false*). Во-первых, это будет однозначно, во-вторых, это ближе к стилю, выбранному для формата (нет ни одного тега, который может принимать пустое значение).

**Comment by vne** [comment]
Звучит логично. Создай, пожалуйста, pull request. Нужно внести изменения в пример, схему (rnc, rng и xsd) и readme.
