### ISSUE TITLE
Альтернатива/встречка/обмен

### ISSUE THREAD

**Issue by ingumsky** [vne/rex-format#7]
В настоящее время формат не предусматривает разделения сделок на «свободную» и «альтернативную» продажи. Возможно, имеет смысл фиксировать «альтернативную» продажу, например, с помощью атрибута **alternate** тега  **type**.

**Comment by vne** [comment]
Мне пока не очень ясно, несколько это общее понятие. Встретилось оно пока только в одном формате. Уточню, как вернусь из отпуска.

**Comment by vne** [comment]
Свободная - это прямая. Альтернативная - это встречка. Это просто вопрос терминологии. Нужно придумать, как это будет записываться в REX. Сделаешь пулл реквест?

**Comment by ingumsky** [comment]
То есть надо разделить продажу на две, так? И в словаре будет больше вариантов, верно? Насчёт терминологии — я не раз встречал названия фирм недвижимости, где использовалось слово «Альтернатива». Мне кажется, это именно из-за термина, а не просто потому, что «есть некая альтернатива», но уверенности у меня, разумеется, нет :)

**Comment by vne** [comment]
Я предлагаю у тега type завести атрибут subtype со своим отдельным словарём order_subtype. Думал ещё про использование "доп. условий сделки", но это, кажется, не совсем то.
Вообще, при проектировании формата я старался не пользоваться атрибутами вообще. Но тут, видимо, подходящий случай.

**Comment by ingumsky** [comment]
М-м-м… Не уверен, что это лучший вариант. Что будет входить в этот словарь?

**Comment by vne** [comment]
В словарь будут входить подвиды сделок

**Comment by ingumsky** [comment]
Давай тогда их сразу здесь перечислим, чтобы я мог их добавить в пулл-реквест ;)

**Comment by vne** [comment]
Давай начнём с прямой и встречки, а дальше будем пополнять по мере необходимости. В старой базе это словарь Id_type, но весь его переносить сюда необходимости нет.

**Comment by ingumsky** [comment]
Субаренда, наверное, тоже сюда должна пойти.

20 августа 2015 г., 18:43 пользователь Vladimir Neverov <
notifications@github.com> написал:

> Давай начнём с прямой и встречки, а дальше будем пополнять по мере
> необходимости. В старой базе это словарь Id_type, но весь его переносить
> сюда необходимости нет.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/vne/rex-format/issues/7#issuecomment-133055928>.
>



-- 
Best regards,
Ivan.

С наилучшими пожеланиями,
Иван.

**Comment by ingumsky** [comment]
Что-то у меня не получается поправить схему в данном случае. Я ориентируюсь
на это:
http://www.relaxng.org/compact-tutorial-20030326.html
Я пытался добавить атрибут к type, который имеет named pattern, но мои
варианты не срабатывают. Расширить существующий паттерн для конкретного
элемента нельзя?

20 августа 2015 г., 23:02 пользователь Ivan Potapov <elsewhere@yandex.ru>
написал:

> Субаренда, наверное, тоже сюда должна пойти.
>
> 20 августа 2015 г., 18:43 пользователь Vladimir Neverov <
> notifications@github.com> написал:
>
>> Давай начнём с прямой и встречки, а дальше будем пополнять по мере
>> необходимости. В старой базе это словарь Id_type, но весь его переносить
>> сюда необходимости нет.
>>
>> —
>> Reply to this email directly or view it on GitHub
>> <https://github.com/vne/rex-format/issues/7#issuecomment-133055928>.
>>
>
>
>
> --
> Best regards,
> Ivan.
>
> С наилучшими пожеланиями,
> Иван.
>



-- 
Best regards,
Ivan.

С наилучшими пожеланиями,
Иван.

**Comment by vne** [comment]
Что-то мне вообще идея с этим отдельным атрибутом не нравится. Она нарушает общую картину. Предлагаю другой вариант.
Свободная продажа - это то, что подразумевается по умолчанию под продажей. Если требуется встречка, это - одно из условий сделки. То же и с субарендой. Давай лучше расширим словарь доп. условий сделки.

**Comment by ingumsky** [comment]
Вот! Именно это я и имел в виду, когда говорил, что мне не нравится.

Sent from my SGS 2
Am 21.08.2015 10:48 schrieb "Vladimir Neverov" <notifications@github.com>:

**Comment by vne** [comment]
Спасибо, смержил.
